### ISSUE TITLE
Casing issue when deploying on Linux Machine 

### ISSUE THREAD

**Issue by icvanee** [EdCharbeneau/BlazorSize#37]
When we deploy our code to a Linux machine (via Azure Pipeline) we get the error message that a file can not be found.
It is looking for BlazorSizeMediaModule.js (with a capital B) but in the Nuget package blazorSizeMediaModule.js is packed (with a lower case b). Can this be fixed?

====
 Could not find file '/root/.nuget/packages/blazorpro.blazorsize/3.0.0/staticwebassets/BlazorSizeMediaModule.js'.
            at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
            at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
            at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
            at Microsoft.NET.Sdk.BlazorWebAssembly.Tools.BrotliCompressCommand.<ExecuteCoreAsync>b__16_0(Int32 i)
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location ---
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()

**Comment by EdCharbeneau** [comment]
Yes, I will publish a new package today.
