### ISSUE TITLE
Error when resizing

### ISSUE THREAD

**Issue by JimCline** [EdCharbeneau/BlazorSize#42]
I am creating a new Blazor app and encountered this error after following the example.

> Uncaught (in promise) Error: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator[[BlazorPro.BlazorSize.MediaQuery, BlazorPro.BlazorSize, Version=3.2.0.0, Culture=neutral, PublicKeyToken=null]].MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator[[BlazorPro.BlazorSize.MediaQuery, BlazorPro.BlazorSize, Version=3.2.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at BlazorPro.BlazorSize.MediaQueryList.MediaQueryChanged(MediaQueryArgs args)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location ---
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson)
    at Object.endInvokeDotNetFromJS (https://localhost:44319/_framework/blazor.webassembly.js:1:4191)
    at Object.invokeJSFromDotNet (https://localhost:44319/_framework/blazor.webassembly.js:1:3797)
    at Object.w [as invokeJSFromDotNet] (https://localhost:44319/_framework/blazor.webassembly.js:1:64287)
    at _mono_wasm_invoke_js_blazor (https://localhost:44319/_framework/dotnet.5.0.3.js:1:190800)
    at do_icall (<anonymous>:wasm-function[10596]:0x194e4e)
    at do_icall_wrapper (<anonymous>:wasm-function[3305]:0x79df9)
    at interp_exec_method (<anonymous>:wasm-function[2155]:0x44ad3)
    at interp_runtime_invoke (<anonymous>:wasm-function[7862]:0x12efff)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[7347]:0x118e5f)
    at do_runtime_invoke (<anonymous>:wasm-function[3304]:0x79d42)

The issue appears to be related to having nested MediaQuery component in razor components.

So I have MediaQueryList around the main layout like this
```csharp
@inherits LayoutComponentBase

<MediaQueryList>
    <div class="page">

        @if(!this.IsSmall)
        {
            <div class="sidebar">
                <NavMenu />
            </div>
        }

        <div class="main">
            <div class="top-row px-4 auth">
                <LoginDisplay />
                <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
            </div>

            <div class="content px-4">
                @Body
            </div>
        </div>        
    </div>

    @if(this.IsSmall)
    {
        <div class="navbar fixed-bottom">
            <NavMenu />
        </div>
    }
    <MediaQuery Media="@Breakpoints.SmallDown" @bind-Matches="this.IsSmall" />
</MediaQueryList>

```

Then I do another MediaQuery in the NavMenu component like this...

```csharp
@if (!this.IsSmall)
{
    <div class="top-row pl-4 navbar navbar-dark">
        <a class="navbar-brand" href="">TrophyReel</a>
        <button class="navbar-toggler" @onclick="ToggleNavMenu">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="@NavMenuCssClass" @onclick="ToggleNavMenu">
        <ul class="nav flex-column">
            <li class="nav-item px-3">
                <NavLink class="nav-link" href="" Match="NavLinkMatch.All">
                    <span class="oi oi-home" aria-hidden="true"></span> Home
                </NavLink>
            </li>
            <li class="nav-item px-3">
                <NavLink class="nav-link" href="counter">
                    <span class="oi oi-plus" aria-hidden="true"></span> Counter
                </NavLink>
            </li>
            <li class="nav-item px-3">
                <NavLink class="nav-link" href="fetchdata">
                    <span class="oi oi-list-rich" aria-hidden="true"></span> Fetch data
                </NavLink>
            </li>
        </ul>
    </div>
}
else
{
   
    <ul class="navbar-nav d-inline">
        <li class="nav-item">
            <NavLink class="nav-link" href="" Match="NavLinkMatch.All">
                <span class="oi oi-home" aria-hidden="true"></span> Home
            </NavLink>
        </li>
        <li class="nav-item">
            <NavLink class="nav-link" href="counter">
                <span class="oi oi-plus" aria-hidden="true"></span> Counter
            </NavLink>
        </li>
        <li class="nav-item">
            <NavLink class="nav-link" href="fetchdata">
                <span class="oi oi-list-rich" aria-hidden="true"></span> Fetch data
            </NavLink>
        </li>
    </ul>
    
}

<MediaQuery Media="@Breakpoints.SmallDown" @bind-Matches="this.IsSmall" />

```

I assumed since the MediaQueryList was at the root any child component would only need the MediaQuery component.

**Comment by EdCharbeneau** [comment]
I'll take a deeper look at this, but I think I have an idea of what's wrong. Your usage looks correct, MediaQueryList is only needed once. However, I feel that the problem is with how the RenderTree works with the nesting here.

```
 @if(!this.IsSmall)
        {
            <div class="sidebar">
                <NavMenu />
            </div>
        }
```

Since NavMenu has a MediaQuery and it is also being toggled via MediaQuery there could be some conflict.

I believe there's a bug here and I'm not dismissing your problem, but in addition to that I want to understand the code example.

If `<NavMenu />` is only shown on large (!IsSmall) then you would never hit the `else` statement inside NavMenu, correct? Thus the second media query is redundant.

**Comment by JimCline** [comment]
Right, the NavMenu also does the mediaquery. If it is not needed, how do I bind to the value in the child component unless I pass it in as a CascadingParameter?

**Comment by JimCline** [comment]
I just reread your question. The intent here is to use the same NavMenu component but have its layout also be responsive. I could have two different components or pass the size value into the NavMenu from the main layout but assumed the nesting would work.

**Comment by EdCharbeneau** [comment]
I'm not sure I communicated this well, or maybe I'm not understanding the usage.

Given the screen is small (isSmall = true), then the NavMenu component is hidden

Given the screen is not small (!isSmall), then the NavMenu component is visible
  When the NavMenu is rendered, then you can assume within the NavMenu that the screen is large

Unless the NavMenu is used outside of this if block, then the second media query is not needed.
```
 @if(!this.IsSmall)
        {
            <div class="sidebar">
                <NavMenu />
            </div>
        }
```

This is all an aside to the actual issue, I'm just offering some help to get a workaround.

**Comment by EdCharbeneau** [comment]
Ok there's some lag in our chat :)

I'll take a look at the nesting issue

**Comment by JimCline** [comment]
Using a CascadingValue to pass the value to child components will work as a workaround for now.

```csharp
<MediaQueryList>
 
    <CascadingValue Value="this.IsSmall" Name="@nameof(Breakpoints.SmallDown)">
        <div class="page">

            @if (!this.IsSmall)
                    {
            <div class="sidebar">
                <NavMenu />
            </div>
            }

            <div class="main">
                <div class="top-row px-4 auth">
                    <LoginDisplay />
                    <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
                </div>

                <div class="content px-4">
                    @Body
                </div>
            </div>
        </div>

        @if (this.IsSmall)
                {
            <div class="navbar fixed-bottom">
                <NavMenu />
            </div>
        }
    </CascadingValue>
    <MediaQuery Media="@Breakpoints.SmallDown" @bind-Matches="this.IsSmall" />
</MediaQueryList>
```

**Comment by EdCharbeneau** [comment]
Nice, I'm glad you're able to move on. But I will bake this into a test project and find out what's causing this to happen. It's for sure a bug.

If you're interested in the details:

BlazorSize attempts to de-duplicate event handlers in JavaScript. So if you have many Breakpoints.SmallDown instances, then they're consolidated down to a single event in JavaScript and dispatched to all of the subscribers in .NET. This is to keep the data serialized across the interop to a minimum. My guess is that something is disposed of before it's able to update the subscriber list.

**Comment by JimCline** [comment]
As as side note, I pulled the code and tried to build the solution myself but it would not run. I assume it was because of the typescript in the BlazorSize library. Do you have build instructions you can add to the ReadMe?

**Comment by EdCharbeneau** [comment]
Sure I can add the instructions.

```bash
npm install
npm run test
npm run build
```

There are two sample projects, one for .NET 5, one for .NET 3. You can run either by using VS or `dotnet run` after building the TS files.

The e2e tests require Telerik Test Studio to run.

**Comment by EdCharbeneau** [comment]
The issue fails on this line. 

https://github.com/EdCharbeneau/BlazorSize/blob/ad26404564ac91ee0b65f0e8c2cb249e646fd9b3/BlazorSize/MediaQuery/MediaQueryService.cs#L50

It appears the collection is being read at the same time the item is removed. I just need more time to identify the lifecycle method that's causing the conflict.

**Comment by EdCharbeneau** [comment]
Thanks for reporting this. I think I have a fix. I'll test and release tomorrow.

**Comment by EdCharbeneau** [comment]
Fixed in 3.2.1

https://www.nuget.org/packages/BlazorPro.BlazorSize/3.2.1
