### ISSUE TITLE
Transitioning from 3.1.0 => 3.2.1 broke ResizeListener DI

### ISSUE THREAD

**Issue by Sipowiz** [EdCharbeneau/BlazorSize#52]
Hi,

I recently updated from 3.1.0 => 3.2.1 and ResizeListener cannot anymore be injected to my components. I get this runtime exception with attached stack trace while trying to load a page that has my MeasuringContainer component (that uses ResizeListener) on it:

`Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot provide a value for property 'Listener' on type 'ELaskuriBlazorWasm.Shared.MeasuringContainer'. There is no registered service of type 'BlazorPro.BlazorSize.ResizeListener'.
System.InvalidOperationException: Cannot provide a value for property 'Listener' on type 'ELaskuriBlazorWasm.Shared.MeasuringContainer'. There is no registered service of type 'BlazorPro.BlazorSize.ResizeListener'.
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass6_0.<CreateInitializer>g__Initialize|2(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()`

Here's how ResizeListener is currently registered to the services container in my Program.cs.

            builder.Services.AddMediaQueryService();

            builder.Services.AddResizeListener(options =>
            {
                options.ReportRate = 50;
            });

Everything worked just fine before the update.

Please help.

**Comment by EdCharbeneau** [comment]
What version of .NET are you using?

**Comment by Sipowiz** [comment]
xx.csproj:

`<TargetFramework>net5.0</TargetFramework>`

**Comment by EdCharbeneau** [comment]
Ah, there's a breaking change on ResizeListener.

Please change the type `ResizeListener` to the interface `IResizeListener`.

`@inject IResizeListener listener`

**Comment by EdCharbeneau** [comment]
This is my mistake, it's possible I should have bumped the major version. Also, my docs are missing this info. Thanks for reporting it.

**Comment by EdCharbeneau** [comment]
Added `@inject IResizeListener listener` to docs and https://github.com/EdCharbeneau/BlazorSize/wiki/BlazorSize-knowledge-base#migration-from-310--321-broke-resizelistener-di

If this doesn't solve your problem, please re-open the issue.

**Comment by Sipowiz** [comment]
> Ah, there's a breaking change on ResizeListener.
> 
> Please change the type `ResizeListener` to the interface `IResizeListener`.
> 
> `@inject IResizeListener listener`

Yeap! That did the trick! 

Thanks for quick reply.

Also awesome job with this lib. Really comes in handy.

br. Ville

**Comment by EdCharbeneau** [comment]
Thanks for the kind words. 🍻 Cheers!

**Comment by Greg90277** [comment]
Hmm - I tried the above and still getting the error:
blazor.server.js:19 
        
       [2022-05-10T18:37:35.886Z] Error: System.InvalidOperationException: Cannot provide a value for property 'ResizeListener' on type 'Live360.Blazor.Server.Shared.MainLayout'. There is no registered service of type 'BlazorPro.BlazorSize.IResizeListener'.
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass5_0.<CreateInitializer>g__Initialize|2(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

**Comment by EdCharbeneau** [comment]
The error `There is no registered service of type 'BlazorPro.BlazorSize.IResizeListener'.` means the service was not registered in Program.cs.

Please post your Program.cs file so I can take a look. Also, make sure this is the Program.cs file of your Blazor application. Sometimes I add things to my Server project by mistake and get these errors.

**Comment by Greg90277** [comment]
Hi Ed.

Thanks for the amazing quick response!

This is Server Side Blazor – all services are declared in the Startup.cs file not Program.cs.

Here are both for reference:

PROGRAM.CS

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Azure.Identity;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Components.Authorization;
using Csla;
using Csla.Configuration;
using Live360.Blazor.Server.Data;
using Live360.Library.Security;
using Live360.Library;
using BlazorPro;
using BlazorPro.BlazorSize;

namespace Live360.Blazor.Server
{

    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStaticWebAssets();
                    webBuilder.UseStartup<Startup>();
                });
    }

}


STARTUP.CS

using Telerik.Reporting.Cache.File;
using Telerik.Reporting.Services;
using Microsoft.Extensions.DependencyInjection.Extensions;
using System.IO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Components.Authorization;
using Csla;
using Csla.Configuration;
using Live360.Blazor.Server.Data;
using Live360.Blazor.Server.Reports;
using Live360.Library.Security;
using Live360.Library;
using BlazorPro;
using BlazorPro.BlazorSize;




namespace Live360.Blazor.Server
{
    public class Startup
    {


        //public IConfiguration Configuration { get; set; }
        private IConfiguration Configuration { get; }


        public Startup(IWebHostEnvironment env)
        {
            //var configurationBuilder = new ConfigurationBuilder()
            //  .AddJsonFile("appsettings.json", true, false);

            // AddEnvironmentVariables allows automatic switching between dev appsettings.json and azure appservice config settings
            var configurationBuilder = new ConfigurationBuilder()
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: true)
                .AddEnvironmentVariables();

            Configuration = configurationBuilder.Build();

            // Test 3/14/2022
            DynamicConnectionManager.InitializeConfiguration(Configuration);

            //Configuration = configuration;


            //Important note on.NET Core
            //By default, ExcelDataReader throws a NotSupportedException "No data is available for encoding 1252." on.NET Core.
            //To fix, add a dependency to the package System.Text.Encoding.CodePages and then add code to register the code page provider during application initialization(f.ex in Startup.cs):
            //System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
            //This is required to parse strings in binary BIFF2-5 Excel documents encoded with DOS - era code pages. These encodings are registered by default in the full .NET Framework, but not on .NET Core.
            System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);


        }


        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddMvc();


            // ORIGINAL TELERIK DEFAULT REPORTING SERVICE
            services.TryAddSingleton<IReportServiceConfiguration>(sp => new ReportServiceConfiguration
            {
                ReportingEngineConfiguration = sp.GetService<IConfiguration>(),
                HostAppId = "Live360",
                Storage = new FileStorage(),
                ReportSourceResolver = new UriReportSourceResolver(
                    System.IO.Path.Combine(GetReportsDir(sp)))
            });

            //  // Try custom JSON resolver
            //  services.TryAddSingleton<IReportServiceConfiguration>(sp => new ReportServiceConfiguration
            //  {
            //      ReportingEngineConfiguration = sp.GetService<IConfiguration>(),
            //      HostAppId = "Live360",
            //      Storage = new FileStorage(),
            //      ReportSourceResolver = new JsonDataSourceReportResolver(
            //System.IO.Path.Combine(GetReportsDir(sp)))
            //       });


            services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
                        .AddCookie();

            services.AddRazorPages().AddNewtonsoftJson();
            services.AddServerSideBlazor();
            services.AddTelerikBlazor();

            services.AddCsla().WithBlazorServerSupport();


            // TEST to see if these two items  alleviate VM problem
            services.AddTransient(typeof(IDataPortal<>), typeof(DataPortal<>));
            services.AddTransient(typeof(Csla.Blazor.ViewModel<>), typeof(Csla.Blazor.ViewModel<>));



            //services.AddSingleton<AuthenticationStateProvider, D1AuthStateProvider>();
            // services.AddSingleton<D1AuthStateProvider>();
            services.AddAuthorizationCore();
            services.AddScoped<
              D1AuthStateProvider,
              D1AuthStateProvider>();
            services.AddScoped<AuthenticationStateProvider>(
              p => p.GetService<D1AuthStateProvider>());


            //services.AddSingleton<WeatherForecastService>();

            services.AddSingleton(Configuration);

            // Try specifying timeouts for SignalR - added 8/2/2021
            services.AddSignalR(hubOptions =>
            {
                hubOptions.EnableDetailedErrors = true;
                // If the server hasn't sent a message within this interval, a ping message is sent automatically
                // to keep the connection open. When changing KeepAliveInterval, change the ServerTimeout/serverTimeoutInMilliseconds setting
                // on the client. The recommended ServerTimeout/serverTimeoutInMilliseconds value is double the KeepAliveInterval value.
                hubOptions.KeepAliveInterval = TimeSpan.FromSeconds(15);
                hubOptions.ClientTimeoutInterval = TimeSpan.FromSeconds(30);
            });

            // New BlazorSize 5/10/2022
            services.AddScoped<ResizeListener>();
            //services.AddResizeListener(options =>
            //                            {
            //                                options.ReportRate = 300;
            //                                options.EnableLogging = false;
            //                                options.SuppressInitEvent = false;
            //                            });
            services.AddMediaQueryService();



        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            // These MUST appear between UseRouting and UseEndpoints!
            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapDefaultControllerRoute();
                endpoints.MapControllers();

                endpoints.MapBlazorHub();
                endpoints.MapFallbackToPage("/_Host");
            });
            app.UseCsla();

        }
        static string GetReportsDir(IServiceProvider sp)
        {
            string fqPath;
             fqPath =  Path.Combine(sp.GetService<IWebHostEnvironment>().ContentRootPath, "Reports");
            DynamicConnectionManager.InitializeReportsFolder(fqPath);
            return fqPath;
        }
    }
}




Greg Dobbs, President
dobbs enterprise solutions, inc.
http://www.dobbs1.com<http://www.dobbs1.com/>
Managing Your Success!

***@***.***

**Comment by EdCharbeneau** [comment]
So there seems to be a typo in the docs. 

Please try the following

```
// incorrect services.AddScoped<ResizeListener>(); 
// Replace with the following
services.AddScoped<IResizeListener, ResizeListener>();

// OR

services.AddResizeListener();

// Or with options

//services.AddResizeListener(options =>
//                            {
//                                options.ReportRate = 300;
//                                options.EnableLogging = false;
//                                options.SuppressInitEvent = false;
//                            });

```

**Comment by Greg90277** [comment]
More info -

Injecting like so:

        // ADDED ResizeListener from BlazorSize 5/10/2022
        [Inject]
        IResizeListener ResizeListener { get; set; }

Results in:

Microsoft.JSInterop.JSException: Could not find 'blazorSizeMedia' in 'window'.
Error: Could not find 'blazorSizeMedia' in 'window'.
    at https://localhost:5001/_framework/blazor.server.js:8:35233
    at Array.forEach (<anonymous>)
    at p (https://localhost:5001/_framework/blazor.server.js:8:35193)
    at https://localhost:5001/_framework/blazor.server.js:8:35903
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.server.js:8:35876)
    at https://localhost:5001/_framework/blazor.server.js:1:20247
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:5001/_framework/blazor.server.js:1:20217)
    at e.processIncomingData (https://localhost:5001/_framework/blazor.server.js:1:18028)
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at BlazorPro.BlazorSize.MediaQueryService.CreateMediaQueryList(DotNetObjectReference`1 dotNetObjectReference)
   at BlazorPro.BlazorSize.MediaQueryList.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)


Greg Dobbs, President
dobbs enterprise solutions, inc.
http://www.dobbs1.com<http://www.dobbs1.com/>
Managing Your Success!

***@***.***

**Comment by Greg90277** [comment]
Hi Ed.

I’ve properly registered the service for the ResizeListener as below
            services.AddResizeListener(options =>
            {
                options.ReportRate = 300;
                options.EnableLogging = true;
                options.SuppressInitEvent = true;
            });

and properly configured the Injected ResizeListener

[Inject]
        public ResizeListener BrowserResizeListener { get; set; }

and added the Event handler

BrowserResizeListener.OnResized += WindowResized;


The onResize event is never invoked and the handler never called.

Server-Side Blazor using the latest version of the Telerik controls. Using BlazorSize 3.21 which is the highest compatible version for my ASP .Net Core project.

Any thoughts?




Greg Dobbs, President
dobbs enterprise solutions, inc.
http://www.dobbs1.com<http://www.dobbs1.com/>
Managing Your Success!

***@***.***

From: Greg Dobbs
Sent: Tuesday, May 10, 2022 3:09 PM
To: EdCharbeneau/BlazorSize ***@***.***>
Subject: RE: [EdCharbeneau/BlazorSize] Transitioning from 3.1.0 => 3.2.1 broke ResizeListener DI (#52)

More info -

Injecting like so:

        // ADDED ResizeListener from BlazorSize 5/10/2022
        [Inject]
        IResizeListener ResizeListener { get; set; }

Results in:

Microsoft.JSInterop.JSException: Could not find 'blazorSizeMedia' in 'window'.
Error: Could not find 'blazorSizeMedia' in 'window'.
    at https://localhost:5001/_framework/blazor.server.js:8:35233
    at Array.forEach (<anonymous>)
    at p (https://localhost:5001/_framework/blazor.server.js:8:35193)
    at https://localhost:5001/_framework/blazor.server.js:8:35903
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.server.js:8:35876)
    at https://localhost:5001/_framework/blazor.server.js:1:20247
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:5001/_framework/blazor.server.js:1:20217)
    at e.processIncomingData (https://localhost:5001/_framework/blazor.server.js:1:18028)
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at BlazorPro.BlazorSize.MediaQueryService.CreateMediaQueryList(DotNetObjectReference`1 dotNetObjectReference)
   at BlazorPro.BlazorSize.MediaQueryList.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)


Greg Dobbs, President
dobbs enterprise solutions, inc.
http://www.dobbs1.com<http://www.dobbs1.com/>
Managing Your Success!

***@***.***

**Comment by Greg90277** [comment]
Hi Ed. Still no go correcting the typo as suggested ..

System.InvalidOperationException: Cannot provide a value for property 'ResizeListener' on type 'Live360.Blazor.Server.Shared.MainLayout'. There is no registered service of type 'BlazorPro.BlazorSize.ResizeListener'.
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass5_0.<CreateInitializer>g__Initialize|2(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()



Greg Dobbs, President
dobbs enterprise solutions, inc.
http://www.dobbs1.com<http://www.dobbs1.com/>
Managing Your Success!

***@***.***

**Comment by EdCharbeneau** [comment]
It looks like the docs are correct, you can also see the samples.

https://github.com/EdCharbeneau/BlazorSize/blob/8632bf001e8d54faf33ee76a05468276e96393fd/BlazorSize.ExampleNet6/Program.cs#L25

Please share your Program.cs if the problem persists.
