### ISSUE TITLE
Lots of unhandled TaskCanceledException's when using MediaQueryService

### ISSUE THREAD

**Issue by SamNibbles** [EdCharbeneau/BlazorSize#56]
Hello,

I recently made the switch over from a `ResizeListener` to the `MediaQueryList` with `MediaQuery` components as it looked much cleaner.

Unfortuantly since making the switch I have been getting lots of unhandled `TaskCancelledException`, which look to be when the `MediaQueryList` is trying to handle disposing.

Below are the logs of the exceptions I am getting out, I am unabled to share the source code though, and have not been able to reproduce in a seperate program unfortunatly, so I am aware this is not a huge amount to go off.

`Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
  Unhandled exception rendering component: A task was canceled.
  System.Threading.Tasks.TaskCanceledException: A task was canceled.
	 at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
	 at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
	 at BlazorPro.BlazorSize.MediaQueryService.RemoveQuery(MediaQuery mediaQuery)
	 at BlazorPro.BlazorSize.MediaQueryList.RemoveQuery(MediaQuery mediaQuery)
	 at BlazorPro.BlazorSize.MediaQuery.DisposeAsync()
	 at Microsoft.AspNetCore.Components.RenderTree.Renderer.<Dispose>g__HandleAsyncExceptions|52_0(List1 tasks)`
	 
`Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
  Unhandled exception in circuit 'WyYJdDMH-7QuyRoaAdIIAjE2bp6ceHC_G9a2aPk-5hM'.
  System.AggregateException: Exceptions were encountered while disposing components. (A task was canceled.) (A task was canceled.)
   ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
	 at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
	 at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
	 at BlazorPro.BlazorSize.MediaQueryService.RemoveQuery(MediaQuery mediaQuery)
	 at BlazorPro.BlazorSize.MediaQueryList.RemoveQuery(MediaQuery mediaQuery)
	 at BlazorPro.BlazorSize.MediaQuery.DisposeAsync()
	 at Microsoft.AspNetCore.Components.RenderTree.Renderer.<Dispose>g__HandleAsyncExceptions|52_0(List1 tasks)
	 --- End of inner exception stack trace ---
   ---> (Inner Exception #1) System.Threading.Tasks.TaskCanceledException: A task was canceled.
	 at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
	 at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
	 at BlazorPro.BlazorSize.MediaQueryService.RemoveQuery(MediaQuery mediaQuery)
	 at BlazorPro.BlazorSize.MediaQueryList.RemoveQuery(MediaQuery mediaQuery)
	 at BlazorPro.BlazorSize.MediaQuery.DisposeAsync()
	 at Microsoft.AspNetCore.Components.RenderTree.Renderer.<Dispose>g__HandleAsyncExceptions|52_0(List1 tasks)<---`

Mainly I am wondering if I am missing something that is causing these errors, or if this is a bug and can be tracked down.

Thanks for any help!

**Comment by longhornleads** [comment]
I have the same problem and would love to get to the bottom of this! If you worked it out, I would love to know how.

**Comment by EdCharbeneau** [comment]
This is a Blazor Server project? Just checking.

I'll look into this tomorrow. I've seen similar issues on the main aspnet repo recently.

**Comment by longhornleads** [comment]
My problems were all related to adding Blazor components to an existing MVC application. I ran into specific problems with the JSInterop changes from .NET CORE 3.1 to .NET 5.0. I was able to resolve everything though quite nicely by changing my approach to use IResizeListener.

**Comment by SamNibbles** [comment]
Yes I am using blazor server as well, I would prefer not to use the IResizeListener if possible as that is what I moved away from as I thought the setup with MediaQuery was much cleaner!

**Comment by EdCharbeneau** [comment]
My research led me to this, it's not promising. It has something to do with GC and Blazor's inability to work properly with it. https://github.com/dotnet/aspnetcore/issues/13026

The discussion got moved to a private thread, so I'm not sure what is happening here.
