### ISSUE TITLE
How to get this Console message: JavaScript interop calls cannot be issued at this time

### ISSUE THREAD

**Issue by ondrejdobecka** [EdCharbeneau/BlazorSize#92]
Hello. Do you have idea how to get rid of this message inside Console ?  I see it many times a day. 
Thanks. Great project!

---- 

fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'frDLBdzqh_avKBHUAxBsyChU-2VplubL98uyXEgZUVI'.
      Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
         at BlazorPro.BlazorSize.MediaQueryService.RemoveQuery(MediaQuery mediaQuery)
         at BlazorPro.BlazorSize.MediaQueryList.RemoveQuery(MediaQuery mediaQuery)
         at BlazorPro.BlazorSize.MediaQuery.DisposeAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()

**Comment by Alexbits** [comment]
Same here. Any updates? Thanks.

**Comment by EdCharbeneau** [comment]
@Alexbits @fseffert @ondrejdobecka Please try 6.2.2 and reopen any issues if the problem persists.
