### ISSUE TITLE
System.InvalidOperationException: JavaScript interop calls cannot be issued at this time.

### ISSUE THREAD

**Issue by Mike-E-angelo** [EdCharbeneau/BlazorSize#93]
I am opening a new issue here to track.  This is in reference to this comment:

https://github.com/EdCharbeneau/BlazorSize/issues/90#issuecomment-1553158530

I can confirm that I am still seeing this error.  Here is the stacktrace in full:

```
System.InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at BlazorPro.BlazorSize.MediaQueryService.RemoveQuery(MediaQuery mediaQuery)
   at BlazorPro.BlazorSize.MediaQueryList.RemoveQuery(MediaQuery mediaQuery)
   at BlazorPro.BlazorSize.MediaQuery.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<Dispose>g__NotifyExceptions|2(List`1 exceptions)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.DisposeAsync()
   at LightInject.Scope.<DisposeAsync>g__Await|14_0(Int32 i, ValueTask vt, List`1 toDispose, HashSet`1 disposedObjects)
   at Microsoft.AspNetCore.Http.Features.RequestServicesFeature.<DisposeAsync>g__Awaited|9_0(RequestServicesFeature servicesFeature, ValueTask vt)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.FireOnCompleted()
```

Please let me know if there is any further information that I can provide and I will assist.

**Comment by TorbjornEliasson** [comment]
Is tehere any update on this error? 
We have intermittent errors from MediaQueryList.
![MediaQueryList error](https://github.com/EdCharbeneau/BlazorSize/assets/71641056/4a57332d-f58a-49c1-9153-30a3dea6c2aa)

**Comment by EdCharbeneau** [comment]
This seems to happen if the client's WebSocket has become disconnected while BlazorSize is processing an event callback. It has been extremely difficult to troubleshoot and reproduce. I'm adding some code to try a capture the exception. I don't like doing this, but it seems to be the only way to suppress the error. 

I am worried about breaking changes when Blazor gets the ability to resume connections. 🤷‍♂️

**Comment by EdCharbeneau** [comment]
Please try 6.2.2 and reopen this issue if the problem continues.

**Comment by HOLz1919** [comment]
The problem persists. I will contribute my idea for a solution.
