### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by newdeal30** [EdCharbeneau/BlazorSize#98]
Hi Ed!,
First, thanks for this great library. I really enjoy your work.
I issued a problem when working with the library on .net 7.
The problem only accours when using Safari on Mac or IOS when the screen size is mobile.
On other browsers or other screen sizes i did not have this problem.
It happens on WebAssembly and on Blazor Server.
Do you have a hint for me?

```
[08:22:35 DBG] Adding entry for MudBlazor.BrowserViewportSubscription/MudBlazor.MudDrawer. 1 total observers after add.
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Collection was modified; enumeration operation may not execute.
      System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
         at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
         at BlazorPro.BlazorSize.MediaQueryService.Initialize(MediaQuery mediaQuery)
         at BlazorPro.BlazorSize.MediaQueryList.Initialize(MediaQuery mediaQuery)
         at BlazorPro.BlazorSize.MediaQuery.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by newdeal30** [comment]
I did a quick and dirty fix which is working for me.
(try/catch at BlazorPro.BlazorSize.MediaQueryService.Initialize(MediaQuery mediaQuery)

Regards Michael

**Comment by EdCharbeneau** [comment]
That's strange behavior. This means that something is trying to modify the MediaQuery cache on MediaQueryList while it is initializing. There is only one moment where the initialize routine iterates the collection, and it does not have any add/remove routines inside. This means components must be getting constructed or disposed during initialization for some reason. I would probably need to see some Razor to understand this. Unfortunately, due to Apple's walled garden, I don't own a device to test this on.

I'm surprised BlazorSize continues to work after adding Try/Catch and ignoring the exception. It could lead to the improper state being reported or events not triggering. But if it works on your machine, I can't really argue with the solution 😁

Is there any chance you could recreate a basic implementation that doesn't have any proprietary code or dependencies and test it on Safari mobile? You can find a bunch of examples in https://github.com/EdCharbeneau/BlazorSize/tree/master/TestComponents

I'm curious if this is a Safari issue, BlazorSize issue, or something related to how your components are using BlazorSize (ex: with MudBlazor).

**Comment by EdCharbeneau** [comment]
Another solution, if you're willing to test it. Remove your try/catch and modify this line:

[[                    foreach (var item in cache.MediaQueries)
                    {
                        item.MediaQueryChanged(cache.Value);](https://github.com/EdCharbeneau/BlazorSize/blob/e4daa618d123c008acae6be4b5fafe7f2b127456/BlazorSize/MediaQuery/MediaQueryService.cs#L83-L85)](https://github.com/EdCharbeneau/BlazorSize/blob/e4daa618d123c008acae6be4b5fafe7f2b127456/BlazorSize/MediaQuery/MediaQueryService.cs#L83-L86C22)

change `cache.MediaQueries` to `cache.MediaQueries.ToList()`

See if that resolves the issue, if it does I'll issue a patch ASAP.

**Comment by newdeal30** [comment]
Hi Ed, 
I will test it on weekend and give you replay.
Thanks

**Comment by newdeal30** [comment]
Would it be a problem to add the try/catch on the official package?
Then I could stay on the official source ;-)

**Comment by EdCharbeneau** [comment]
My worry is catching an error and swallowing it could lead to instability issues that would be hard to troubleshoot because the exception is hidden. 

I'll have to find a way to make it optional, maybe some sort of compatibility flag that is an option parameter.

**Comment by StevenRasmussen** [comment]
I am running into this as well.  I can reproduce on EDGE mobile... but also if I use EDGE on a desktop and use the developer tools and force it to emulate a mobile screen.

**Comment by StevenRasmussen** [comment]
I feel like the issue might be when you use this in conjunction with the `AuthorizeView` component.

Here is the code to my component that causes issues:

```razor
@using System.Security.Claims
@using BlazorPro.BlazorSize

@inject NavigationManager _navigationManager

<AuthorizeView>
    <Authorized>
        <div class="d-flex flex-row align-items-center gap-3">
            <div class="d-flex flex-row align-items-center gap-2 pointer-cursor" id="accountId" @onclick="@(() => _accountMenuOpen = !_accountMenuOpen)">
                <FluentIcon Icon="Icons.Filled.Size24.PersonCircle" />
                @if (!_isSmall)
                {
                    @context.User.FindFirstValue(ClaimTypes.GivenName)
                }
            </div>
            <div @onclick="@(() => _navigationManager.Logout())" style="cursor:pointer">
                Log out
            </div>
        </div>
    </Authorized>
    <NotAuthorized>
        <div class="d-flex flex-row align-items-center gap-3">
            <div class="pointer-cursor" @onclick="@(() => _navigationManager.NavigateToLoginPage())">login</div>
        </div>
    </NotAuthorized>
</AuthorizeView>

<MediaQuery Media="@Breakpoints.XSmallDown" @bind-Matches=_isSmall />

@code {
    private bool _accountMenuOpen = false;
    private bool _isSmall;

    private void NavigateToRoute(string route)
    {
        this._navigationManager.NavigateTo(route);
    }
}
```

If I comment out the `<MediaQuery>` component then I do not have the issue.

**Comment by EdCharbeneau** [comment]
@StevenRasmussen I was still unable to reproduce the error. I tried the sample from above, along with using the Edge mobile view. 🤷‍♂️

Sorry I can't help, this has been difficult to repro.

**Comment by Mike-E-angelo** [comment]
I am running into this issue.  In my case I have three components on the same page that each have their own MediaQuery and for some reason they are stomping on each other and generating this error.  I recently took out some asynchronous code that delayed the initialization for components while calls were made to the database.  Now that this is gone this issue has presented itself.

**Comment by nrhoffmann** [comment]
We have also encountered this issue. @EdCharbeneau What can we do about it? Can we make the libraries Initialize tolerant of adds and removes?

**Comment by EdCharbeneau** [comment]
@nrhoffmann Can you provide more details?

Error message, even if it's the same as above.
Browser's used.
Blazor Render modes used.

**Comment by nrhoffmann** [comment]
@EdCharbeneau This is on Desktop Chrome using lib version 8.0.0 (b/c we are still on .net8) and using Interactive WebAssembly rendering.

```
Uncaught (in promise) Error: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator[[BlazorPro.BlazorSize.MediaQuery, BlazorPro.BlazorSize, Version=6.2.0.0, Culture=neutral, PublicKeyToken=null]].MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator[[BlazorPro.BlazorSize.MediaQuery, BlazorPro.BlazorSize, Version=6.2.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at BlazorPro.BlazorSize.MediaQueryList.MediaQueryChanged(MediaQueryArgs args)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
--- End of stack trace from previous location ---
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson)
    at b.endInvokeDotNetFromJS (https://localhost:7295/_framework/blazor.webassembly.js:1:3136)
    at Object.gn [as endInvokeDotNetFromJS] (https://localhost:7295/_framework/blazor.webassembly.js:1:58943)
    at https://localhost:7295/_framework/dotnet.runtime.8.0.11.v4d3uixg8h.js:3:178446
    at Ll (https://localhost:7295/_framework/dotnet.runtime.8.0.11.v4d3uixg8h.js:3:179280)
    at wasm://wasm/00b2166a:wasm-function[349]:0x1f99a
    at wasm://wasm/00b2166a:wasm-function[245]:0x1be41
    at wasm://wasm/00b2166a:wasm-function[238]:0xf00e
    at wasm://wasm/00b2166a:wasm-function[272]:0x1d05f
    at wasm://wasm/00b2166a:wasm-function[3186]:0xe87c6
    at wasm://wasm/00b2166a:wasm-function[2506]:0xbe4ba
```

**Comment by EdCharbeneau** [comment]
It says in the error message that you're on `Version=6.2.0.0`, can you update to version 8.0.0? I believe there's error handling in version 8.0 that will help with this.

**Comment by nrhoffmann** [comment]
@EdCharbeneau I must have pulled that stacktrace from the prod version of our app that is not on 8.0.0. I will reach out again if we continue to have problems. Thanks for all your help and for sharing this awesome lib with the community.
